# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: required
apt_packages:
- unixodbc-dev
- libarchive-dev

script: 
  - |
    travis_wait 50 R CMD build .
    travis_wait 50 R CMD check *tar.gz

after_failure:
- find *Rcheck -name '*.fail' -print -exec cat '{}' \;
# show memory usage again
- sudo free -m -t
# show actions of the OOM killer
- sudo dmesg

r_github_packages:
 - jimhester/archive
 - ajdamico/lodown


before_install:
# shutdown servies on Travis, which may have a memory impact
# show memory usage before and after shutdown of services
- sudo service --status-all
- sudo free -m -t
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- sudo free -m -t

env:
 - this_sample_break=1
 - this_sample_break=2
 - this_sample_break=3
 - this_sample_break=4
 - this_sample_break=5
 - this_sample_break=6
 - this_sample_break=7
 - this_sample_break=8
 - this_sample_break=9
 - this_sample_break=10
 - this_sample_break=11
 - this_sample_break=12
 - this_sample_break=13
 - this_sample_break=14
 - this_sample_break=15
 - this_sample_break=16
 - this_sample_break=17
 - this_sample_break=18
 - this_sample_break=19
 - this_sample_break=20
 - this_sample_break=21
 - this_sample_break=22
 - this_sample_break=23
 - this_sample_break=24
 - this_sample_break=25
 - this_sample_break=26
 - this_sample_break=27
 - this_sample_break=28
 - this_sample_break=29
 - this_sample_break=30
 - this_sample_break=31
 - this_sample_break=32
 - this_sample_break=33
 - this_sample_break=34
 - this_sample_break=35
 - this_sample_break=36
 - this_sample_break=37
 - this_sample_break=38
 - this_sample_break=39
 - this_sample_break=40
 - this_sample_break=41
 - this_sample_break=42
 - this_sample_break=43
 - this_sample_break=44
 - this_sample_break=45
 - this_sample_break=46
 - this_sample_break=47
 - this_sample_break=48
 - this_sample_break=49
 - this_sample_break=50
 - this_sample_break=51
 - this_sample_break=52
 - this_sample_break=53
 - this_sample_break=54
 - this_sample_break=55
 - this_sample_break=56
 - this_sample_break=57
 - this_sample_break=58
 - this_sample_break=59
 - this_sample_break=60
 - this_sample_break=61
 - this_sample_break=62
 - this_sample_break=63
 - this_sample_break=64
 - this_sample_break=65
 - this_sample_break=66
 - this_sample_break=67
 - this_sample_break=68
 - this_sample_break=69
 - this_sample_break=70
 - this_sample_break=71
 - this_sample_break=72
 - this_sample_break=73
 - this_sample_break=74
 - this_sample_break=75
 - this_sample_break=76
 - this_sample_break=77
 - this_sample_break=78
 - this_sample_break=79
 - this_sample_break=80
 - this_sample_break=81
 - this_sample_break=82
 - this_sample_break=83
 - this_sample_break=84
 - this_sample_break=85
 - this_sample_break=86
 - this_sample_break=87
 - this_sample_break=88
 - this_sample_break=89
 - this_sample_break=90
 - this_sample_break=91
 - this_sample_break=92
 - this_sample_break=93
 - this_sample_break=94
 - this_sample_break=95
 - this_sample_break=96
 - this_sample_break=97
 - this_sample_break=98
 - this_sample_break=99
 - this_sample_break=100
matrix:
    fast_finish: true
